# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/stayease
spring.datasource.username=postgres
spring.datasource.password=admin123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=stayease-super-secret-key-minimum-256-bits-long-for-security
jwt.expiration=86400000
spring.security.user.name=disabled
spring.security.user.password=disabled
logging.level.org.springframework.security=TRACE
